for level in {0..3}; do
    test_folder="final_pipeline_data/collected_diffuse_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_gauss_diffuse/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_gauss_med/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_med_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_preprocessing/collected_images_reti_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_diffuse_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_gauss_diffuse/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_gauss_med/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_med_gauss/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_preprocessing/compressed_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_images_dark/collected_images_dark_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_diffuse/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_diffuse/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/collected_med/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
    test_folder="final_pipeline_data/miotcd_med/filtered_images_quality_${level}"
	touch "${test_folder}_report.txt"
	python evaluate_binary_classifier.py --model-path model/resnet18_binary_best.pth --data-dir "$test_folder" > "${test_folder}_report.txt"
done
